services:
  proxy:
    image: itzg/mc-proxy:latest
    ports:
      - "0.0.0.0:25565:25565"
      - "0.0.0.0:25565:25565/udp"
    environment:
      TYPE: "VELOCITY"
      VELOCITY_VERSION: "latest"
      MEMORY: "512M"
      USE_AIKAR_FLAGS: true
      ICON: "https://github.com/miners-online/.github/blob/main/profile/logos/favicon-64x64.png?raw=true"
      PLUGINS_FILE: /extras/plugins.txt
      # Configs
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_DB_HOST: "10.0.0.143:3306"
      CFG_DB_NAME: "minecraft_permissions"
      CFG_DB_USERNAME: "minecraft"
      CFG_DB_PASSWORD: ${CFG_DB_PASSWORD}
      CFG_DB_REDIS_HOST: "10.0.0.143:6379"
      CFG_DB_REDIS_USERNAME: "default"
      CFG_DB_REDIS_PASSWORD: ${CFG_DB_REDIS_PASSWORD}
      CFG_FORWARDING_SECRET: ${CFG_FORWARDING_SECRET}
    volumes:
      - ./data/proxy:/config
    restart: always

  lobby-1:
    image: itzg/minecraft-server:latest
    environment:
      EULA: TRUE
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      MEMORY: "1024M"
      DIFFICULTY: peaceful
      USE_AIKAR_FLAGS: true
      ONLINE_MODE: false
      MODPACK: http://10.0.0.12:82/server_setup/lobby-1/mods.zip
      WORLD: http://10.0.0.12:82/server_setup/lobby-1/world.tar.gz
      REMOVE_OLD_MODS: true
      # Configs
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_DB_HOST: "10.0.0.143:3306"
      CFG_DB_NAME: "minecraft_permissions"
      CFG_DB_USERNAME: "minecraft"
      CFG_DB_PASSWORD: ${CFG_DB_PASSWORD}
      CFG_DB_REDIS_HOST: "10.0.0.143:6379"
      CFG_DB_REDIS_USERNAME: "default"
      CFG_DB_REDIS_PASSWORD: ${CFG_DB_REDIS_PASSWORD}
      CFG_FORWARDING_SECRET: ${CFG_FORWARDING_SECRET}
    volumes:
      - ./data/lobby-1:/config
    restart: always