services:
  proxy:
    image: itzg/mc-proxy:latest
    healthcheck:
      test: ["NONE"]
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
      - target: 25565
        published: 25565
        protocol: udp
        mode: host
      - target: 19132
        published: 19132
        protocol: tcp
        mode: host
      - target: 19132
        published: 19132
        protocol: udp
        mode: host
    user: "0:0"
    env_file:
      - ./.env
    environment:
      TYPE: "CUSTOM"
      BUNGEE_JAR_FILE: "/config/server.jar"
      VELOCITY_VERSION: "latest"
      MEMORY: "512M"
      USE_AIKAR_FLAGS: "true"
      ICON: "https://github.com/miners-online/.github/blob/main/profile/logos/favicon-64x64.png?raw=true"
      PLUGINS_FILE: /extras/plugins.txt
      # Configs
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_FORWARDING_SECRET: ${FORWARDING_SECRET}
      UID: "0"
      GID: "0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/proxy:/config
      - ./data/proxy/plugins.txt:/extras/plugins.txt
      - ./data/proxy/forwarding.secret.yml:/config/forwarding.secret.yml
      - ./data/proxy/velocity.toml:/server/velocity.toml:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  lobby:
    image: itzg/minecraft-server:latest
    env_file:
      - ./.env
    environment:
      EULA: "TRUE"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "http://10.0.0.12:82/server_setup/lobby-1/server.jar"
      VERSION: "1.21.1"
      MEMORY: "1024M"
      DIFFICULTY: peaceful
      USE_AIKAR_FLAGS: "true"
      ONLINE_MODE: "false"
      WORLD: http://10.0.0.12:82/server_setup/lobby-1/world.zip
      REMOVE_OLD_MODS: "true"
      # Configs
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_FORWARDING_SECRET: ${FORWARDING_SECRET}
      APPLY_VELOCITY_RCON: "true"
    labels:
      - "velocity.enable=true"
      - "velocity.port=25565"
      - "velocity.group=lobby"
    volumes:
      - ./data/lobby-1:/config
    deploy:
      replicas: 2
      restart_policy:
        condition: any